config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    member do
      post '/comments' => 'boards#create_comment', as: :create_comment_to
      delete '/comments/:comment_id' => 'boards#delete_comment', as: :delete_comment_to
      patch '/comments/:comment_id' => 'boards#update_comment', as: :update_comment_to
    end

    collection do
      get '/:board_id/like' => 'boards#user_like_board', as: :user_like
      get '/page_scroll' => 'boards#page_scroll', as: :scroll
    end
  end

  root 'boards#index'

  # sign in
  get '/signin' => 'sessions#signin', as: :user_signin # 로그인 페이지
  post '/signin' => 'sessions#user_signin' # , as: :user_signin # 실제 로그인 기능

  # sign up
  get '/signup' => 'sessions#signup', as: :user_signup # 회원가입 페이지
  post '/signup' => 'sessions#user_signup' # , as: :user_signup # 실제 회원가입 기능
  post '/check_email' => 'sessions#check_email' # email 유효성 검사 기능
  post '/check_password' => 'sessions#check_password' # password와 password_confirmation이 같은지 확인

  # sign out
  delete '/signout' => 'sessions#signout', as: :user_signout # 로그아웃 기능
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :likes

  paginates_per 50

  def require_permission?(user)
    self.user.id == user.id # 이글을 작성한 user의 id(self.user.id)가 파라미터로 넘어온 user의 id와 같습니까? 같으면 true, 다르면 false.
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :board

  def require_permission?(user)
    self.user.id == user.id # 이글을 작성한 user의 id(self.user.id)가 파라미터로 넘어온 user의 id와 같습니까? 같으면 true, 다르면 false.
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :board

  def require_permission?(user)
    self.user.id == user.id # 이글을 작성한 user의 id(self.user.id)가 파라미터로 넘어온 user의 id와 같습니까? 같으면 true, 다르면 false.
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password #암호화된 비밀번호를 가지고 있다는 것을 표시 / password를 통해 password_digest에 암호화된 비밀번호를 가지고 있습니다.
  has_many :boards
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :user_signed_in?

  # 로그인 한 사람만 어플리케이션에 접근이 가능하도록 하기 위한 부분
  def current_user
    # 현재 접속한 유저
    @current_user ||= User.find(session[:user_id])
  end

  def user_signed_in?
    # 유저가 로그인 했는지 여부(boolean) / ?가 있는 친구는 boolean타입으로 리턴하는 것이 약속
    # session[:user_id] 비어있으면 >> 로그인 안한거 >> false 리턴
    # session[:user_id] 채워져있으면 >> 로그인 한거 >> true 리턴
    !session[:user_id].nil? # .nil?이 붙으면 boolean 타입으로 리턴이 된다. / 확실하게 true와 false로 나오게 하고 싶을 때 사용 / sesstion[:user_id]라고 써도 기능은 비슷하지만 session[:user_id]는 값이 있을 경우 그 값을 리턴해준다.
  end

  def authenticate_user!
    # ! = bang => 내용물을 변화시킬 수 있는 메소드에 붙여줌
    # element.upcase! => element 자체가 변화함
    # element.upcase => return 값이 변화함

    # 유저가 로그인 했다면 진행
    # 유저가 로그인 하지 않았다면 로그인 페이지로
    if session[:user_id].nil?
      redirect_to '/signin', notice: "로그인이 필요합니다."
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, exception: [:index, :show]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.order("created_at DESC").page(params[:page]) # page는 kaminari가 제공하는 메소드?이다. 홈에서 url뒤에 ?page=2 이런식으로 하면 다음 페이지로 넘어간다.
  end

  def page_scroll
    @boards = Board.order("created_at DESC").page(params[:page])
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    if user_signed_in?
      @like = Like.where(user_id: current_user.id, board_id: params[:id])
    else
      @like = []
    end
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def user_like_board
    @like = Like.where(user_id: current_user.id, board_id: params[:board_id]).first

    # 만약에 좋아요를 이미 누른 상태라면
    unless @like.nil?
      @like.destroy
      puts '좋아요 취소'

    # 만약에 처음 좋아요를 누른 상태라면 (좋아요를 누를 수 있는 상태)
    else
      @like = Like.create(user_id: current_user.id, board_id: params[:board_id])
      puts '좋아요 누름'
    end
  end

  def user_dislike_board

  end

  def create_comment
    @comment = Comment.create(
      user_id: current_user.id,
      board_id: params[:id],
      contents: params[:contents]
    )
  end

  def delete_comment
    @comment = Comment.find(params[:comment_id])
    if @comment.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  def update_comment
    @comment = Comment.find(params[:comment_id])
    @comment.update(
      contents: params[:contents]
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :contents)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # 회원가입
  def signup # 회원가입하는 화면이 보여짐
  end

  def user_signup # 실제로 회원가입하는 기능 구현
    user = User.new(
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )
    if user.save
      redirect_to '/signin', notice: "회원가입 완료!"
    else
      redirect_to '/signup', notice: "잘못된 비밀번호입니다."
    end
  end

  # 이메일 유효성 검사
  def check_email
    @tmp = params[:email]
    @email = User.find_by(email: params[:email]).nil?
  end

  # password와 password_confirmation이 같은지 확인
  def check_password
    @pw = params[:password]
    @pw_confir = params[:password_confirmation]
  end

  # 로그인
  def signin #로그인 화면이 보여짐
  end

  def user_signin #실제로 로그인하는 기능 구현
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password]) #authenticate라는 메소드는 bcrypt에 달려있는 메소드 / user가 있고 그 user의 email과 입력한 password가 일치하는지 확인
        session[:user_id] = user.id
        redirect_to '/', notice: "로그인에 성공했습니다."
    else
      redirect_to '/signin', notice: "이메일이 없거나, 비밀번호가 틀렸습니다."
    end
  end

  # 로그아웃
  def signout
    session.delete(:user_id) # session.clear와 똑같음
    redirect_to '/', notice: "로그아웃 성공!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit '작성하기', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/boards/create_comment.js.erb
// 5. 댓글을 보여주는 table의 tbody에 추가해 줌.
$('.comment-list').prepend(`
    <tr id="comment-<%= @comment.id %>">
      <td class="comment" data-id="<%= @comment.id %>"><%= @comment.contents %></td>
      <td></td>
      <td><button class="btn btn-outline-danger delete-comment" data-id="<%= @comment.id %>"><i class="fas fa-trash-alt fa-spin"></i>삭제</button></td>
    </tr>
  `);
// 6. input 태그를 비워줌
$('#comment-input').val('');

app/views/boards/delete_comment.js.erb
alert("댓글 삭제 요청이 왔어요!!!");
$("#comment-<%= @comment.id %>").fadeOut().remove(); // 내용물을 잠시 숨겨두는 것은 hide() / 다이나믹하게 사라지게 하는 것은 fadeOut()

app/views/boards/destroy.js.erb
alert("자바스크립트로 요청이 왔어요!!!")

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to '글보기', @board, class: 'btn btn-primary' %> |
<%= link_to '홈으로', boards_path, class: 'btn btn-dark' %>

app/views/boards/index.html.erb
<%= link_to '새글쓰기', new_board_path, class: 'btn btn-dark' %>
<a class='btn btn-warning' id='change-title'>제목 바꾸기</a>
<a class='btn btn-danger color-btn' kaka="text-danger">빨강</a>
<a class='btn btn-primary color-btn' kaka="text-primary">파랑</a>
<a class='btn btn-warning color-btn' kaka="text-warning">노랑</a>

<table class="table table-hover text-center">
  <thead>
    <tr>
      <th>글번호</th>
      <th>제목</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody class="boards">
    <% @boards.each do |board| %>
      <tr class="content" data-id="<%= board.id %>">
        <td><%= board.id %></td>
        <td class="title"><%= board.title %></td>
        <!-- <td><%= link_to '보기', board, class: 'btn btn-primary' %></td>
        <td><%= link_to '수정', edit_board_path(board), class: 'btn btn-success' %></td>
        <td><%= link_to '삭제', board, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% content_for :script do %>
  <script>
    $(document).ready(function(){

      // setInterval(function(){alert("hello"};)}, 3000)
      $('.boards').on('click', '.board', function() { // tr_location.js.erb에 있던 내용 가져옴
        location.href = '/boards/' + $(this).data('id'); // $(this).data('id') == $(this).attr('data-id')
      })
      var page_count = 2;
      setInterval(function() {
        // 1. 화면 최하단에 도착했을 때
        console.log("hoho");
        if ($(window).scrollTop() >= $(document).height() - $(window).height()){
          console.log("제일 아래 도착했다!!");

          // 2. 추가적인 40개의 element에 대한 요청을 보냄
          $.ajax({
            url: '/boards/page_scroll',
            method: 'GET',
            data: {
              page: page_count++
            }
          })
          // 3. 요청해서 응답으로 받은 element를 최하단에 추가
        }
        // console.log('스크롤 움직인다다다다다다');
        // console.log("window.scrollTop() : " + $(window).scrollTop());
        // console.log("document.height() : " + $(document).height());
        // console.log("window.height() : " + $(window).height());
      }, 3000)
    })
  </script>
  <!-- <script src="tr_location.js"></script> -->
  <script src="change_title.js"></script>
  <script src="change_color.js"></script>
<% end %>

app/views/boards/new.html.erb
<h1>새글쓰기</h1>

<%= render 'form' %>

<%= link_to '홈으로', boards_path, class: 'btn btn-dark' %>

app/views/boards/page_scroll.js.erb
alert("페이지 추가할께요.");
$('.boards').append(`
    <% @boards.each do |board| %>
      <tr class="content" data-id="<%= board.id %>">
        <td><%= board.id %></td>
        <td class="title"><%= board.title %></td>
      </tr>
    <% end %>
  `)

app/views/boards/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @board.contents %>
</p>
<% if user_signed_in? and @board.require_permission?(current_user) %>
  <%= link_to '<i class="fas fa-edit fa-spin"></i> 수정'.html_safe, edit_board_path(@board), class: 'btn btn-warning' %> |
  <%= link_to '<i class="fas fa-trash-alt"></i> 삭제'.html_safe, @board, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %> |
  <button class="btn btn-outline-danger delete"><i class="fas fa-edit fa-spin"></i>삭제</button> |
<% end %>
<%= link_to '<i class="fas fa-home"></i> 홈으로'.html_safe, boards_path, class: 'btn btn-dark' %> |
<% if @like.length > 0 %>
  <!-- <a href="/boards/<%= @board.id %>/like"> -->
  <button type="button" class="btn btn-primary like"><i class="fas fa-thumbs-up"></i>좋아요(<span id="like-count"><%= @board.likes.count %></span>)</button>
<% else %>
  <!-- <a href="/boards/<%= @board.id %>/like"> -->
    <button type="button" class="btn btn-outline-primary like"><i class="fas fa-thumbs-up"></i>좋아요(<span id="like-count"><%= @board.likes.length %></span>)</button>
<% end %>

<form class="form-inline my-2 my-lg-2" id="comment-form">
  <input class="form-control mr-sm-2" id="comment-input" type="text" placeholder="Comment">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-pencil-alt fa-spin"></i>댓글쓰기</button>
</form>

<table class="table">
  <thead>
    <tr>
      <th width="70%">내용</th>
      <th width="15%"></th>
      <th width="15%"></th>
    </tr>
  </thead>
  <tbody class="comment-list">
    <% @board.comments.reverse.each do |comment| %>
      <tr id="comment-<%= comment.id %>">
        <td class="comment" data-id="<%= comment.id %>"><%= comment.contents %></td>
        <td></td>
        <td><button class="btn btn-outline-danger delete-comment" data-id="<%= comment.id %>"><i class="fas fa-trash-alt fa-spin"></i>삭제</button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% content_for :script do %>
<script>
  $(function() {
    // 1. 좋아요 버튼을 눌렀을 때
    $('.like').on('click', function(){
      // 2. ajax를 이용해서 /board/:board_id/like라는 url에 요청을 보냄
      $.ajax({
        url: '/boards/<%= @board.id %>/like',
        method: "GET"
      })
    })


    // 댓글 추가 기능
    // 1. form이 제출(submit)되면
    $('#comment-form').on('submit', function(e) {
      // 2. form의 기본 이벤트를 막아주고
      e.preventDefault();
      // 3. form 안의 input 태그에서 입력한 값을 가져온 다음
      var value = $('#comment-input').val();
      // 4. 해당 겂을 댓글을 등록하는 url로 보냄. (ajax를 사용해서)
      $.ajax({
        url: '/boards/<%= @board.id %>/comments',
        method: 'POST',
        data: {
          contents: value
        }
      });
    });

    // 게시글 삭제하기
    $('.delete').on('click', function() {
      $.ajax({
        url: "<%= board_path(@board) %>.js",
        method: "DELETE"
      });
    });

    // 댓글 삭제하기
    $('.comment-list').on('click', '.delete-comment', function() {
      var id = $(this).data('id');
      $.ajax({
        url: '/boards/<%= @board.id %>/comments/' + id,
        method: "DELETE"
      });
    });

    // 댓글 수정하기
    // 1. 댓글 내용이 들어있는 td태그 부분을 누르면
    $('.comment-list').on('click', '.comment', function() {

      // 하나의 input 창이 열려있는 경우, 추가적인 input 창을 못열게
      if ($(this).parents('.comment-list').find('.comment-form').length > 0) { // 이미열려있는 comment form이 있다면
        alert("이미 수정 중인 comment가 있습니다.");
        return false;
      }

      var text = $(this).text();
      var id = $(this).data('id');
      console.log(id);

      // 3. 수정 완료 버튼을 삭제버튼 옆에 추가한다.
      $(this).siblings()[0].innerHTML = "<button class='btn btn-success update-comment' type='submit'><i class='fas fa-edit fa-spin'></i>수정완료</button>";

      // 2. 해당 부분을 댓글 내용이 들어있는 input 태그로 바꾸고
      $(this).replaceWith(`<td class="edit-comment"><input class="form-control comment-form" value="${text}"><input class="comment-id" type="hidden" value="${id}"></td>`);
    });


    // 완료 버튼을 누르면 작성했던 내용이 서버로 가서 저장(update)
    $('.comment-list').on('click', '.update-comment', function() {
      // 1. input 태그에 있는 내용물을 뽑아서 서버로 보냄
      var text = $('.comment-form').val();
      var id = $('.comment-id').val();
      $.ajax({
        url: '/boards/<%= @board.id %>/comments/' + id,
        method: "PATCH", // 혹은 PUT가능
        data: {
          contents: text
        }
      })
    });
  })
</script>
<% end %>

app/views/boards/update_comment.js.erb
alert("댓글 수정 완료!");
// 2. input 태그가 있는 부분을 다시 일반 td 태그로 변환
$('.edit-comment').replaceWith(`<td class="comment" data-id="<%= @comment.id %>"><%= @comment.contents %></td>`);
// 3. 완료버튼 삭제
$('.update-comment').remove();

app/views/boards/user_like_board.js.erb
// 좋아요 기능
alert("좋아요 버튼 누름");
$('.like').toggleClass('btn-outline-primary btn-primary');
var like_count = parseInt($('#like-count').text());
if(<%= @like.frozen? %>) { // 데이터가 destroy되면 db에서는 날아가지만 메모리에서 바로 삭제가 되는 것이 아니라 얼려버려서 사용할 수 없게 만드는 것이다.
                           // 여기서 frozen? 이러고 묻는 것은 삭제했냐고 묻는 것이다.
  $('#like-count').text(like_count - 1);
}
else { // 좋아요를 눌른 상태니?
  $('#like-count').text(like_count + 1);
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JsClass</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <!-- 이거 추가하면 디바이스의 화면 크기에 따라 어플리케이션의 화면크기가 조정된다. -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
     <a class="navbar-brand" href="#">Navbar</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarsExampleDefault">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item">
           <a class="nav-link" href="/">Home</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">Board</a>
         </li>
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">User</a>
           <div class="dropdown-menu" aria-labelledby="dropdown01">
            <% if user_signed_in? %>
              <a class="dropdown-item"><%= current_user.email %></a>
              <%= link_to 'Sign out', user_signout_path, class: "dropdown-item", data: {method: :delete, confirm: "로그아웃 하시겠습니까?"} %>
            <% else %>
              <%= link_to 'Sign in', user_signin_path, class: "dropdown-item" %>
              <%= link_to 'Sign up', user_signup_path, class: "dropdown-item" %>
            <% end %>
           </div>
         </li>
       </ul>
     </div>
   </nav>

  <div class="container" style="margin-top: 5rem !important;"> <!-- mt-5 => margin top=5 mt-5는 5가 끝이라서 더 크게 할 수 없다. -->
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <%= yield %> <!-- controller#action 에 해당하는 view파일을 찾는다. -->
  </div>
  <%= yield :script %> <!-- content_for :script를 찾는다. -->

  <script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>

</body>
</html>